# Generated by Django 2.2.7 on 2020-05-13 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profile_img')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(default='speaker', max_length=100)),
                ('facebook', models.URLField(blank=True, max_length=950)),
                ('twitter', models.URLField(blank=True, max_length=950)),
                ('slug', models.SlugField(default='Change-me', max_length=300)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='THIS SHOULD BE A SHORT TITLE', max_length=80)),
                ('small_desc', models.TextField(default='THIS SHOULD BE A SHORT DESCRIPTION', max_length=100)),
                ('topic_type', models.CharField(choices=[('Normal', 'Normal'), ('Main', 'Main')], default=('Normal', 'Normal'), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=700)),
                ('video', models.FileField(upload_to='topic_files')),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='topic',
            field=models.ForeignKey(on_delete=None, to='topic.Topic'),
        ),
    ]
